### ISSUE TITLE
not working with Attrition Extended Overhaul

### ISSUE THREAD

**Issue by thisisyoursus** [zga163/iLiskarm#2]
[SCRIPT SV] [errr] COMPILE ERROR Undefined variable "AddCallback_IsValidMeleeExecutionTarget"
[SCRIPT SV] [errr] /modai/extra_ai_spawner.gnut line [566] column [41]

**Comment by MintStar4517** [comment]
"My mod has modified the relevant files for melee detection to implement the energy theft execution feature. You might try temporarily deleting TitanPassiveEX\mod\scripts\vscripts\melee. After running it normally, you can try merging it again."

**Comment by MintStar4517** [comment]
"Moreover, the files from the Attrition Extended mode may have many modified files similar to mine, which could lead to conflicts. Due to loading priority issues, some files may not be loaded.that was .... terrible I recommend trying the regular TTDM mode first."
